USE ambientalistas;

-- 1. Departamento (50 filas)
INSERT INTO Departamento (nombre) VALUES ('Antioquia');
INSERT INTO Departamento (nombre) VALUES ('Cundinamarca');
INSERT INTO Departamento (nombre) VALUES ('Valle del Cauca');
INSERT INTO Departamento (nombre) VALUES ('Atlántico');
INSERT INTO Departamento (nombre) VALUES ('Bolívar');
INSERT INTO Departamento (nombre) VALUES ('Santander');
INSERT INTO Departamento (nombre) VALUES ('Norte de Santander');
INSERT INTO Departamento (nombre) VALUES ('Huila');
INSERT INTO Departamento (nombre) VALUES ('Tolima');
INSERT INTO Departamento (nombre) VALUES ('Quindío');
INSERT INTO Departamento (nombre) VALUES ('Risaralda');
INSERT INTO Departamento (nombre) VALUES ('Cauca');
INSERT INTO Departamento (nombre) VALUES ('Putumayo');
INSERT INTO Departamento (nombre) VALUES ('Nariño');
INSERT INTO Departamento (nombre) VALUES ('Meta');
INSERT INTO Departamento (nombre) VALUES ('Arauca');
INSERT INTO Departamento (nombre) VALUES ('Casanare');
INSERT INTO Departamento (nombre) VALUES ('Boyacá');
INSERT INTO Departamento (nombre) VALUES ('Caldas');
INSERT INTO Departamento (nombre) VALUES ('Cesar');
INSERT INTO Departamento (nombre) VALUES ('Chocó');
INSERT INTO Departamento (nombre) VALUES ('La Guajira');
INSERT INTO Departamento (nombre) VALUES ('Magdalena');
INSERT INTO Departamento (nombre) VALUES ('Sucre');
INSERT INTO Departamento (nombre) VALUES ('San Andrés y Providencia');
INSERT INTO Departamento (nombre) VALUES ('Vichada');
INSERT INTO Departamento (nombre) VALUES ('Guainía');
INSERT INTO Departamento (nombre) VALUES ('Vaupés');
INSERT INTO Departamento (nombre) VALUES ('Amazonas');
INSERT INTO Departamento (nombre) VALUES ('Córdoba');
INSERT INTO Departamento (nombre) VALUES ('San Jorge');
INSERT INTO Departamento (nombre) VALUES ('El Guavio');
INSERT INTO Departamento (nombre) VALUES ('Sierra Nevada');
INSERT INTO Departamento (nombre) VALUES ('Laguna Verde');
INSERT INTO Departamento (nombre) VALUES ('Río Claro');
INSERT INTO Departamento (nombre) VALUES ('Montaña Azul');
INSERT INTO Departamento (nombre) VALUES ('Páramo Dorado');
INSERT INTO Departamento (nombre) VALUES ('Selva Oscura');
INSERT INTO Departamento (nombre) VALUES ('Valle Escondido');
INSERT INTO Departamento (nombre) VALUES ('Ciénaga Real');
INSERT INTO Departamento (nombre) VALUES ('Monte Carmelo');
INSERT INTO Departamento (nombre) VALUES ('Punta del Sol');
INSERT INTO Departamento (nombre) VALUES ('Estrella del Sur');
INSERT INTO Departamento (nombre) VALUES ('Brisas del Norte');
INSERT INTO Departamento (nombre) VALUES ('Loma del Sol');
INSERT INTO Departamento (nombre) VALUES ('Prado Verde');
INSERT INTO Departamento (nombre) VALUES ('Monteverde');
INSERT INTO Departamento (nombre) VALUES ('Laguna Mística');
INSERT INTO Departamento (nombre) VALUES ('Río Blanco');
INSERT INTO Departamento (nombre) VALUES ('Campo Alegre');

-- 2. Entidad (50 filas)
INSERT INTO Entidad (nombre) VALUES ('Corporación Ambiental Verde');
INSERT INTO Entidad (nombre) VALUES ('Fundación Naturaleza Viva');
INSERT INTO Entidad (nombre) VALUES ('EcoAmigos');
INSERT INTO Entidad (nombre) VALUES ('ProNaturaleza');
INSERT INTO Entidad (nombre) VALUES ('Vida y Tierra');
INSERT INTO Entidad (nombre) VALUES ('Bosques del Futuro');
INSERT INTO Entidad (nombre) VALUES ('Agua Pura');
INSERT INTO Entidad (nombre) VALUES ('Planeta Sostenible');
INSERT INTO Entidad (nombre) VALUES ('Conservación Sin Fronteras');
INSERT INTO Entidad (nombre) VALUES ('Red Ecológica');
INSERT INTO Entidad (nombre) VALUES ('Guardianes del Bosque');
INSERT INTO Entidad (nombre) VALUES ('Huellas Verdes');
INSERT INTO Entidad (nombre) VALUES ('Alianza Ambiental');
INSERT INTO Entidad (nombre) VALUES ('EcoRumbo');
INSERT INTO Entidad (nombre) VALUES ('Misión Verde');
INSERT INTO Entidad (nombre) VALUES ('Naturaleza y Vida');
INSERT INTO Entidad (nombre) VALUES ('Protege la Tierra');
INSERT INTO Entidad (nombre) VALUES ('Semillas del Mañana');
INSERT INTO Entidad (nombre) VALUES ('EcoGuardianes');
INSERT INTO Entidad (nombre) VALUES ('Verde Esperanza');
INSERT INTO Entidad (nombre) VALUES ('Planeta Vivo');
INSERT INTO Entidad (nombre) VALUES ('Ambiente Sano');
INSERT INTO Entidad (nombre) VALUES ('Fuerza Natural');
INSERT INTO Entidad (nombre) VALUES ('Conexión Ecológica');
INSERT INTO Entidad (nombre) VALUES ('Respira Vida');
INSERT INTO Entidad (nombre) VALUES ('Amanecer Verde');
INSERT INTO Entidad (nombre) VALUES ('Tierra Viva');
INSERT INTO Entidad (nombre) VALUES ('Rumbo Sostenible');
INSERT INTO Entidad (nombre) VALUES ('EcoFuturo');
INSERT INTO Entidad (nombre) VALUES ('Jardín de la Vida');
INSERT INTO Entidad (nombre) VALUES ('Vida Ecológica');
INSERT INTO Entidad (nombre) VALUES ('Naturaleza Unida');
INSERT INTO Entidad (nombre) VALUES ('EcoAcción');
INSERT INTO Entidad (nombre) VALUES ('Caminos Verdes');
INSERT INTO Entidad (nombre) VALUES ('Horizonte Ambiental');
INSERT INTO Entidad (nombre) VALUES ('Ecos de la Tierra');
INSERT INTO Entidad (nombre) VALUES ('Armonía Natural');
INSERT INTO Entidad (nombre) VALUES ('EcoMundo');
INSERT INTO Entidad (nombre) VALUES ('Energía Verde');
INSERT INTO Entidad (nombre) VALUES ('Tierra y Futuro');
INSERT INTO Entidad (nombre) VALUES ('EcoGuardianes del Sur');
INSERT INTO Entidad (nombre) VALUES ('Amigos del Planeta');
INSERT INTO Entidad (nombre) VALUES ('Voces Verdes');
INSERT INTO Entidad (nombre) VALUES ('Soluciones Naturales');
INSERT INTO Entidad (nombre) VALUES ('Renacer Ambiental');
INSERT INTO Entidad (nombre) VALUES ('Verde y Vivo');
INSERT INTO Entidad (nombre) VALUES ('EcoSalud');
INSERT INTO Entidad (nombre) VALUES ('Cultura Verde');
INSERT INTO Entidad (nombre) VALUES ('Visión Ambiental');
INSERT INTO Entidad (nombre) VALUES ('EcoInnovación');

-- 3. Parque (50 filas)
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Nacional Natural Tayrona', '2005-03-15');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural Los Nevados', '2006-04-10');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico de la Sabana', '2007-05-20');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural Chingaza', '2008-06-25');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Nacional Natural El Cocuy', '2009-07-30');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico La Laguna', '2010-08-15');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural Farallones de Cali', '2011-09-05');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Nacional Natural Corales del Rosario', '2012-10-10');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural Paramillo', '2013-11-20');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico La Guajira', '2014-12-15');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Nacional Natural Puracé', '2005-01-10');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural Matarredonda', '2006-02-20');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico El Tuparro', '2007-03-15');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Nacional Natural Amacayacu', '2008-04-25');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural Utría', '2009-05-30');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico El Paujil', '2010-06-10');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Nacional Natural Sierra de la Macarena', '2011-07-20');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural La Tatacoa', '2012-08-25');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico Cañón del Chicamocha', '2013-09-30');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Nacional Natural El Cocuy II', '2014-10-15');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico El Paraíso', '2005-11-05');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural La Corchuela', '2006-12-10');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico Piedra Sentada', '2007-01-20');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Nacional Natural Serranía de la Macarena', '2008-02-25');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural Los Páramos', '2009-03-30');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico El Encanto', '2010-04-15');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Nacional Natural Sumapaz', '2011-05-20');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural Jardín Botánico', '2012-06-25');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico El Oso', '2013-07-30');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Nacional Natural Minca', '2014-08-15');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural Los Altos', '2005-09-05');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico del Sol', '2006-10-10');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Nacional Natural Montaña Mística', '2007-11-20');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural Cascada del Río', '2008-12-15');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico Bosque Encantado', '2009-01-10');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Nacional Natural Laguna de Fúquene', '2010-02-20');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural Valle Escondido', '2011-03-15');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico El Paraíso Verde', '2012-04-25');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Nacional Natural Cumbre del Aire', '2013-05-30');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural Reserva de la Biosfera', '2014-06-10');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico El Mirador', '2005-07-20');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Nacional Natural Serranía Azul', '2006-08-25');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural Río Claro', '2007-09-30');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico Brisas del Valle', '2008-10-15');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Nacional Natural Monte Carmelo', '2009-11-05');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural Estrella del Sur', '2010-12-10');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico La Selva', '2011-01-20');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Nacional Natural Loma del Sol', '2012-02-25');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Natural Tierra y Vida', '2013-03-30');
INSERT INTO Parque (nombre, fecha_declaracion) VALUES ('Parque Ecológico Campo Alegre', '2014-04-15');

-- 4. Area (50 filas)
INSERT INTO Area (id_parque, nombre, superficie) VALUES (3, 'Área Bosque Frondoso', 150.75);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (7, 'Área de Humedales', 89.50);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (12, 'Área de Montaña', 210.30);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (5, 'Zona de Conservación', 95.20);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (10, 'Área de Flora y Fauna', 180.00);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (2, 'Área de Reforestación', 130.45);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (15, 'Zona Ecológica', 160.80);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (20, 'Área de Investigación', 75.60);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (25, 'Área de Protección', 200.00);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (30, 'Área de Recreación', 110.00);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (35, 'Área de Bosque Nativo', 140.20);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (40, 'Zona de Conservación de Aves', 98.75);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (45, 'Área de Vida Silvestre', 210.10);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (50, 'Área de Rehabilitación', 125.30);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (1, 'Área de Diversidad', 145.60);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (4, 'Área de Descanso', 80.90);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (6, 'Zona de Exploración', 170.00);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (8, 'Área de Páramos', 190.25);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (9, 'Zona de Estudio', 115.50);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (11, 'Área de Reservas Naturales', 165.75);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (13, 'Área de Aves Migratorias', 130.00);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (14, 'Área de Recolección', 120.10);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (16, 'Zona de Plantaciones', 105.40);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (17, 'Área de Uso Múltiple', 95.00);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (18, 'Área de Especies Endémicas', 155.85);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (19, 'Zona de Recuperación', 85.60);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (21, 'Área de Educación Ambiental', 140.00);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (22, 'Área de Conservación Marina', 190.50);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (23, 'Zona de Observación', 130.30);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (24, 'Área de Conservación de Plantas', 175.25);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (26, 'Área de Protegidos', 165.00);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (27, 'Zona de Biodiversidad', 115.80);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (28, 'Área de Reproducción', 105.95);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (29, 'Área de Control', 95.75);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (31, 'Zona de Ecoeducación', 120.00);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (32, 'Área de Paisaje Natural', 135.20);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (33, 'Zona de Conservación Acuática', 150.00);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (34, 'Área de Recuperación Forestal', 110.60);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (36, 'Zona de Protección Ambiental', 140.40);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (37, 'Área de Manejo Ambiental', 125.80);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (38, 'Zona de Conservación Cultural', 115.30);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (39, 'Área de Investigación Silvestre', 130.75);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (41, 'Zona de Reforestación Urbana', 105.00);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (42, 'Área de Preservación', 150.50);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (43, 'Zona de Recuperación de Ecosistemas', 160.20);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (44, 'Área de Desarrollo Sostenible', 95.30);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (46, 'Zona de Conservación Integral', 125.60);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (47, 'Área de Investigaciones Ambientales', 110.40);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (48, 'Zona de Protección de Recursos', 135.90);
INSERT INTO Area (id_parque, nombre, superficie) VALUES (49, 'Área de Innovación Ambiental', 145.00);

-- 5. Especie (50 filas)
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Quercus robur', 'Roble común');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Pinus sylvestris', 'Pino silvestre');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Eucalyptus globulus', 'Eucalipto');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Acacia dealbata', 'Mimosa');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Ficus carica', 'Higuera');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Betula pendula', 'Abedul');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Acer pseudoplatanus', 'Arce');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Fraxinus excelsior', 'Fresno');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Alnus glutinosa', 'Aliso');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Salix alba', 'Sauce blanco');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Populus nigra', 'Chopo negro');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Ulmus minor', 'Olmo menor');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Castanea sativa', 'Castaño');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Juglans regia', 'Nogal común');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Prunus avium', 'Ciruelo silvestre');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Corylus avellana', 'Avellano');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Magnolia grandiflora', 'Magnolia');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Liquidambar styraciflua', 'Ámbar');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Platanus occidentalis', 'Plátano occidental');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Ginkgo biloba', 'Ginkgo');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Cedrus libani', 'Cedro del Líbano');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Sequoia sempervirens', 'Secuoya');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Araucaria araucana', 'Pehuén');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Bambusa vulgaris', 'Bambú común');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Olea europaea', 'Oliva');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Citrus sinensis', 'Naranja');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Citrus limon', 'Limón');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Morus alba', 'Mora blanca');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Vitis vinifera', 'Uva común');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Cucurbita pepo', 'Calabaza');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Solanum lycopersicum', 'Tomate');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Capsicum annuum', 'Pimiento');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Zea mays', 'Maíz');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Triticum aestivum', 'Trigo');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Oryza sativa', 'Arroz');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Phaseolus vulgaris', 'Frijol común');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Glycine max', 'Soja');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Avena sativa', 'Avena');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Hordeum vulgare', 'Cebada');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Secale cereale', 'Centeno');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Brassica oleracea', 'Col');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Daucus carota', 'Zanahoria');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Allium cepa', 'Cebolla');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Allium sativum', 'Ajo');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Solanum tuberosum', 'Papa');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Beta vulgaris', 'Remolacha');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Cichorium intybus', 'Achicoria');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Lactuca sativa', 'Lechuga');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Coriandrum sativum', 'Cilantro');
INSERT INTO Especie (nombre_cientifico, nombre_vulgar) VALUES ('Petroselinum crispum', 'Perejil');

-- 6. Personal (50 filas)
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1001', 'Carlos López', 'Calle 12 #34-56, Medellín', '444-1234', '300-1111111', 1500000.00, 'Gestión');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1002', 'María González', 'Carrera 5 #67-89, Bogotá', '444-2345', '300-2222222', 1300000.00, 'Vigilancia');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1003', 'Juan Martínez', 'Avenida 3 #45-67, Cali', '444-3456', '300-3333333', 1200000.00, 'Conservación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1004', 'Ana Rodríguez', 'Calle 7 #89-10, Barranquilla', '444-4567', '300-4444444', 1400000.00, 'Investigación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1005', 'Luis Hernández', 'Carrera 2 #23-45, Cartagena', '444-5678', '300-5555555', 1550000.00, 'Gestión');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1006', 'Sofía Pérez', 'Avenida 8 #12-34, Bucaramanga', '444-6789', '300-6666666', 1350000.00, 'Vigilancia');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1007', 'Miguel Sánchez', 'Calle 9 #98-76, Pereira', '444-7890', '300-7777777', 1250000.00, 'Conservación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1008', 'Laura Díaz', 'Carrera 1 #11-22, Manizales', '444-8901', '300-8888888', 1450000.00, 'Investigación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1009', 'Andrés Ramírez', 'Avenida 4 #33-44, Santa Marta', '444-9012', '300-9999999', 1500000.00, 'Gestión');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1010', 'Isabel Romero', 'Calle 10 #55-66, Villavicencio', '444-0123', '300-1010101', 1300000.00, 'Vigilancia');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1011', 'Felipe Torres', 'Carrera 3 #77-88, Ibagué', '444-1235', '300-1112223', 1200000.00, 'Conservación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1012', 'Patricia Rojas', 'Avenida 5 #99-00, Pasto', '444-2346', '300-2223334', 1400000.00, 'Investigación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1013', 'Diego Morales', 'Calle 11 #21-32, Armenia', '444-3457', '300-3334445', 1550000.00, 'Gestión');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1014', 'Camila Vargas', 'Carrera 4 #43-54, Montería', '444-4568', '300-4445556', 1350000.00, 'Vigilancia');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1015', 'Jorge Castillo', 'Avenida 6 #65-76, Neiva', '444-5679', '300-5556667', 1250000.00, 'Conservación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1016', 'Daniela Herrera', 'Calle 12 #87-98, Sincelejo', '444-6780', '300-6667778', 1450000.00, 'Investigación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1017', 'Ricardo Molina', 'Carrera 7 #12-34, Pasto', '444-7891', '300-7778889', 1500000.00, 'Gestión');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1018', 'Elena Cruz', 'Avenida 2 #56-78, Cali', '444-8902', '300-8889990', 1300000.00, 'Vigilancia');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1019', 'Oscar Vega', 'Calle 3 #78-90, Bogotá', '444-9013', '300-1011121', 1200000.00, 'Conservación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1020', 'Verónica Ruiz', 'Carrera 8 #90-12, Medellín', '444-0124', '300-1213141', 1400000.00, 'Investigación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1021', 'Ramón Aguirre', 'Avenida 7 #34-56, Barranquilla', '444-1236', '300-1314151', 1550000.00, 'Gestión');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1022', 'Catalina Mendoza', 'Calle 4 #67-89, Cartagena', '444-2347', '300-1415161', 1350000.00, 'Vigilancia');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1023', 'Esteban Navarro', 'Carrera 9 #12-34, Bucaramanga', '444-3458', '300-1516171', 1250000.00, 'Conservación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1024', 'Rebeca Silva', 'Avenida 10 #23-45, Pereira', '444-4569', '300-1617181', 1450000.00, 'Investigación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1025', 'Gustavo Pineda', 'Calle 5 #34-56, Manizales', '444-5670', '300-1718191', 1500000.00, 'Gestión');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1026', 'Adriana Figueroa', 'Carrera 6 #45-67, Santa Marta', '444-6781', '300-1819201', 1300000.00, 'Vigilancia');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1027', 'Javier Orozco', 'Avenida 11 #56-78, Villavicencio', '444-7892', '300-1920211', 1200000.00, 'Conservación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1028', 'Lorena Bravo', 'Calle 7 #67-89, Ibagué', '444-8903', '300-2021221', 1400000.00, 'Investigación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1029', 'Mauricio Ríos', 'Carrera 12 #78-90, Pasto', '444-9014', '300-2122231', 1550000.00, 'Gestión');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1030', 'Silvia Moreno', 'Avenida 3 #89-01, Armenia', '444-0125', '300-2223241', 1350000.00, 'Vigilancia');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1031', 'Raúl León', 'Calle 8 #90-12, Montería', '444-1237', '300-2324251', 1250000.00, 'Conservación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1032', 'Natalia Jiménez', 'Carrera 10 #01-23, Neiva', '444-2348', '300-2425261', 1450000.00, 'Investigación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1033', 'Andrés Castillo', 'Avenida 9 #12-34, Sincelejo', '444-3459', '300-2526271', 1500000.00, 'Gestión');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1034', 'Paula Rincón', 'Calle 6 #23-45, Pasto', '444-4570', '300-2627281', 1300000.00, 'Vigilancia');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1035', 'Héctor Delgado', 'Carrera 11 #34-56, Cali', '444-5671', '300-2728291', 1200000.00, 'Conservación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1036', 'Marta Galindo', 'Avenida 2 #45-67, Bogotá', '444-6782', '300-2829301', 1400000.00, 'Investigación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1037', 'Pablo Serrano', 'Calle 9 #56-78, Medellín', '444-7893', '300-2930311', 1550000.00, 'Gestión');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1038', 'Verónica Castro', 'Carrera 1 #67-89, Barranquilla', '444-8904', '300-3031321', 1350000.00, 'Vigilancia');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1039', 'Oscar Peña', 'Avenida 4 #78-90, Cartagena', '444-9015', '300-3132331', 1250000.00, 'Conservación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1040', 'Inés Martínez', 'Calle 10 #89-01, Bucaramanga', '444-0126', '300-3233341', 1450000.00, 'Investigación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1041', 'Guillermo Fuentes', 'Carrera 3 #90-12, Pereira', '444-1238', '300-3334351', 1500000.00, 'Gestión');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1042', 'Cecilia Peña', 'Avenida 5 #01-23, Manizales', '444-2349', '300-3435361', 1300000.00, 'Vigilancia');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1043', 'Estela Miranda', 'Calle 7 #12-34, Santa Marta', '444-3450', '300-3536371', 1200000.00, 'Conservación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1044', 'Tomás Aguirre', 'Carrera 8 #23-45, Villavicencio', '444-4560', '300-3637381', 1400000.00, 'Investigación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1045', 'Rosa Muñoz', 'Avenida 6 #34-56, Ibagué', '444-5672', '300-3738391', 1550000.00, 'Gestión');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1046', 'Diego Lozano', 'Calle 11 #45-67, Pasto', '444-6783', '300-3839401', 1350000.00, 'Vigilancia');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1047', 'Alejandra Ríos', 'Carrera 9 #56-78, Armenia', '444-7894', '300-3940411', 1250000.00, 'Conservación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1048', 'Fernando Solís', 'Avenida 10 #67-89, Montería', '444-8905', '300-4041421', 1450000.00, 'Investigación');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1049', 'Catalina Ibáñez', 'Calle 5 #78-90, Neiva', '444-9016', '300-4142431', 1500000.00, 'Gestión');
INSERT INTO Personal (cedula, nombre, direccion, telefono, movil, sueldo, rol) VALUES ('1050', 'Samuel Andrade', 'Carrera 11 #89-01, Sincelejo', '444-0127', '300-4243441', 1300000.00, 'Vigilancia');

-- 7. Vehiculo (50 filas)
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camioneta', 'Toyota Hilux');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Motocicleta', 'Honda');
INSERT INTO Vehiculo (tipo, marca) VALUES ('4x4', 'Jeep Wrangler');
INSERT INTO Vehiculo (tipo, marca) VALUES ('SUV', 'Ford Explorer');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camion', 'Mercedes-Benz Actros');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Bicicleta', 'Giant');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camioneta', 'Nissan Navara');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Motocicleta', 'Yamaha');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Pickup', 'Chevrolet Colorado');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camioneta', 'Ford Ranger');
INSERT INTO Vehiculo (tipo, marca) VALUES ('SUV', 'Jeep Cherokee');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camion', 'Volvo FH');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Motocicleta', 'Kawasaki Ninja');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Bicicleta', 'Specialized');
INSERT INTO Vehiculo (tipo, marca) VALUES ('4x4', 'Land Rover Defender');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camioneta', 'Mitsubishi L200');
INSERT INTO Vehiculo (tipo, marca) VALUES ('SUV', 'Honda CR-V');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camion', 'Scania R-Series');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Pickup', 'Toyota Hilux');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Motocicleta', 'Ducati');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camioneta', 'Chevrolet S10');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Bicicleta', 'Trek');
INSERT INTO Vehiculo (tipo, marca) VALUES ('4x4', 'Jeep Grand Cherokee');
INSERT INTO Vehiculo (tipo, marca) VALUES ('SUV', 'Hyundai Santa Fe');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camion', 'MAN TGX');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Pickup', 'Ford F-150');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Motocicleta', 'Suzuki GSX');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camioneta', 'Nissan Frontier');
INSERT INTO Vehiculo (tipo, marca) VALUES ('SUV', 'Kia Sorento');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camion', 'Iveco Stralis');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Bicicleta', 'Cannondale');
INSERT INTO Vehiculo (tipo, marca) VALUES ('4x4', 'Jeep Wrangler');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Motocicleta', 'Harley Davidson');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camioneta', 'Chevrolet Silverado');
INSERT INTO Vehiculo (tipo, marca) VALUES ('SUV', 'Toyota RAV4');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camion', 'Mercedes-Benz Actros');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Pickup', 'Ram 1500');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Bicicleta', 'Scott');
INSERT INTO Vehiculo (tipo, marca) VALUES ('4x4', 'Land Rover Defender');
INSERT INTO Vehiculo (tipo, marca) VALUES ('SUV', 'Ford Escape');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camioneta', 'Mitsubishi Triton');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Motocicleta', 'Yamaha YZF-R3');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camion', 'Volvo FM');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Pickup', 'Chevrolet Colorado');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Bicicleta', 'Giant');
INSERT INTO Vehiculo (tipo, marca) VALUES ('4x4', 'Jeep Wrangler');
INSERT INTO Vehiculo (tipo, marca) VALUES ('SUV', 'Honda Pilot');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camioneta', 'Nissan X-Trail');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Motocicleta', 'KTM');
INSERT INTO Vehiculo (tipo, marca) VALUES ('Camion', 'Scania P-Series');

-- 8. Proyecto_Investigacion (50 filas)
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (5000000.00, '2018-01-15', '2018-07-15');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (7500000.00, '2018-02-10', '2018-08-10');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (6200000.00, '2018-03-05', '2018-09-05');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8300000.00, '2018-04-20', '2018-10-20');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (9100000.00, '2018-05-15', '2018-11-15');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (5400000.00, '2018-06-10', '2018-12-10');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (7600000.00, '2018-07-01', '2019-01-01');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8800000.00, '2018-08-12', '2019-02-12');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (6700000.00, '2018-09-05', '2019-03-05');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (9900000.00, '2018-10-10', '2019-04-10');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (5800000.00, '2018-11-15', '2019-05-15');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8200000.00, '2018-12-20', '2019-06-20');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (7500000.00, '2019-01-10', '2019-07-10');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (9300000.00, '2019-02-05', '2019-08-05');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (6800000.00, '2019-03-15', '2019-09-15');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8500000.00, '2019-04-10', '2019-10-10');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (7100000.00, '2019-05-05', '2019-11-05');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (9200000.00, '2019-06-15', '2019-12-15');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (6400000.00, '2019-07-20', '2020-01-20');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8700000.00, '2019-08-25', '2020-02-25');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8000000.00, '2019-09-10', '2020-03-10');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (9100000.00, '2019-10-05', '2020-04-05');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (7500000.00, '2019-11-15', '2020-05-15');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8800000.00, '2019-12-20', '2020-06-20');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8200000.00, '2020-01-10', '2020-07-10');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (9600000.00, '2020-02-05', '2020-08-05');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (7000000.00, '2020-03-15', '2020-09-15');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8400000.00, '2020-04-10', '2020-10-10');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (7800000.00, '2020-05-05', '2020-11-05');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (9000000.00, '2020-06-15', '2020-12-15');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8300000.00, '2020-07-10', '2021-01-10');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (9500000.00, '2020-08-05', '2021-02-05');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (7700000.00, '2020-09-15', '2021-03-15');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8800000.00, '2020-10-10', '2021-04-10');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8100000.00, '2020-11-05', '2021-05-05');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (9200000.00, '2020-12-15', '2021-06-15');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8600000.00, '2021-01-10', '2021-07-10');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (9900000.00, '2021-02-05', '2021-08-05');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (7500000.00, '2021-03-15', '2021-09-15');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8700000.00, '2021-04-10', '2021-10-10');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8000000.00, '2021-05-05', '2021-11-05');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (9100000.00, '2021-06-15', '2021-12-15');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8400000.00, '2021-07-10', '2022-01-10');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (9600000.00, '2021-08-05', '2022-02-05');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (7800000.00, '2021-09-15', '2022-03-15');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (9000000.00, '2021-10-10', '2022-04-10');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8300000.00, '2021-11-05', '2022-05-05');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (9500000.00, '2021-12-15', '2022-06-15');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (7700000.00, '2022-01-10', '2022-07-10');
INSERT INTO Proyecto_Investigacion (presupuesto, fecha_inicio, fecha_fin) VALUES (8800000.00, '2022-02-05', '2022-08-05');

-- 9. Visitante (50 filas)
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V001', 'Alejandro Ruiz', 'Calle 15 #23-45, Medellín', 'Ingeniero', '2022-03-01', '2022-03-05');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V002', 'Camila Torres', 'Carrera 7 #89-10, Bogotá', 'Arquitecta', '2022-03-02', '2022-03-06');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V003', 'Diego Molina', 'Avenida 4 #12-34, Cali', 'Biólogo', '2022-03-03', '2022-03-07');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V004', 'Valentina Gómez', 'Calle 8 #45-67, Barranquilla', 'Docente', '2022-03-04', '2022-03-08');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V005', 'Sebastián Pérez', 'Carrera 2 #23-45, Cartagena', 'Periodista', '2022-03-05', '2022-03-09');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V006', 'Mariana Ramírez', 'Avenida 6 #78-90, Bucaramanga', 'Médica', '2022-03-06', '2022-03-10');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V007', 'Andrés Vargas', 'Calle 11 #12-34, Pereira', 'Abogado', '2022-03-07', '2022-03-11');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V008', 'Isabella Moreno', 'Carrera 9 #56-78, Manizales', 'Contadora', '2022-03-08', '2022-03-12');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V009', 'Francisco Rojas', 'Avenida 3 #67-89, Santa Marta', 'Empresario', '2022-03-09', '2022-03-13');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V010', 'Juliana Castillo', 'Calle 5 #78-90, Villavicencio', 'Artista', '2022-03-10', '2022-03-14');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V011', 'Mateo Delgado', 'Carrera 4 #90-12, Ibagué', 'Arquitecto', '2022-03-11', '2022-03-15');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V012', 'Renata Silva', 'Avenida 7 #12-34, Pasto', 'Ingeniera', '2022-03-12', '2022-03-16');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V013', 'Esteban Morales', 'Calle 6 #23-45, Armenia', 'Doctor', '2022-03-13', '2022-03-17');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V014', 'Daniela Navarro', 'Carrera 8 #34-56, Montería', 'Psicóloga', '2022-03-14', '2022-03-18');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V015', 'Luis Herrera', 'Avenida 9 #45-67, Neiva', 'Periodista', '2022-03-15', '2022-03-19');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V016', 'Sofía Acosta', 'Calle 10 #56-78, Sincelejo', 'Abogada', '2022-03-16', '2022-03-20');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V017', 'Julián Martínez', 'Carrera 3 #67-89, Medellín', 'Biólogo', '2022-03-17', '2022-03-21');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V018', 'Gabriela Rincón', 'Avenida 4 #78-90, Bogotá', 'Ingeniera Ambiental', '2022-03-18', '2022-03-22');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V019', 'Tomás Espinosa', 'Calle 7 #89-10, Cali', 'Profesor', '2022-03-19', '2022-03-23');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V020', 'Carolina Suárez', 'Carrera 5 #90-12, Barranquilla', 'Diseñadora', '2022-03-20', '2022-03-24');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V021', 'Martín Fuentes', 'Avenida 6 #12-34, Cartagena', 'Empresario', '2022-03-21', '2022-03-25');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V022', 'Lucía Camacho', 'Calle 8 #23-45, Bucaramanga', 'Médica', '2022-03-22', '2022-03-26');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V023', 'Iván Ortega', 'Carrera 2 #34-56, Pereira', 'Ingeniero', '2022-03-23', '2022-03-27');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V024', 'Andrea Castillo', 'Avenida 3 #45-67, Manizales', 'Arquitecta', '2022-03-24', '2022-03-28');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V025', 'Héctor Mendoza', 'Calle 9 #56-78, Santa Marta', 'Biólogo', '2022-03-25', '2022-03-29');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V026', 'Paula Ruiz', 'Carrera 4 #67-89, Villavicencio', 'Contadora', '2022-03-26', '2022-03-30');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V027', 'Nicolás Ríos', 'Avenida 7 #78-90, Ibagué', 'Abogado', '2022-03-27', '2022-03-31');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V028', 'Sara Paredes', 'Calle 5 #89-01, Pasto', 'Ingeniera', '2022-03-28', '2022-04-01');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V029', 'Juan Camacho', 'Carrera 8 #90-12, Armenia', 'Doctor', '2022-03-29', '2022-04-02');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V030', 'Elena Vega', 'Avenida 9 #01-23, Montería', 'Psicóloga', '2022-03-30', '2022-04-03');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V031', 'Marco Salinas', 'Calle 10 #12-34, Neiva', 'Periodista', '2022-03-31', '2022-04-04');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V032', 'Claudia Soto', 'Carrera 3 #23-45, Sincelejo', 'Abogada', '2022-04-01', '2022-04-05');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V033', 'Felipe Navarro', 'Avenida 4 #34-56, Medellín', 'Biólogo', '2022-04-02', '2022-04-06');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V034', 'Mónica Aguirre', 'Calle 7 #45-67, Bogotá', 'Ingeniera Ambiental', '2022-04-03', '2022-04-07');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V035', 'Raquel Mendoza', 'Carrera 5 #56-78, Cali', 'Arquitecta', '2022-04-04', '2022-04-08');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V036', 'Andrés Cárdenas', 'Avenida 6 #67-89, Barranquilla', 'Profesor', '2022-04-05', '2022-04-09');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V037', 'Lourdes Prieto', 'Calle 8 #78-90, Cartagena', 'Diseñadora', '2022-04-06', '2022-04-10');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V038', 'Sergio Rojas', 'Carrera 2 #89-01, Bucaramanga', 'Empresario', '2022-04-07', '2022-04-11');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V039', 'Cecilia Marín', 'Avenida 3 #90-12, Pereira', 'Médica', '2022-04-08', '2022-04-12');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V040', 'Bruno Flores', 'Calle 9 #01-23, Manizales', 'Ingeniero', '2022-04-09', '2022-04-13');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V041', 'Verónica Lozano', 'Carrera 4 #12-34, Santa Marta', 'Arquitecta', '2022-04-10', '2022-04-14');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V042', 'Guillermo Castillo', 'Avenida 7 #23-45, Villavicencio', 'Biólogo', '2022-04-11', '2022-04-15');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V043', 'Patricio Rivas', 'Calle 5 #34-56, Ibagué', 'Contador', '2022-04-12', '2022-04-16');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V044', 'Rosa Jiménez', 'Carrera 8 #45-67, Pasto', 'Abogada', '2022-04-13', '2022-04-17');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V045', 'Esteban Molina', 'Avenida 9 #56-78, Armenia', 'Ingeniero', '2022-04-14', '2022-04-18');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V046', 'Laura Delgado', 'Calle 10 #67-89, Montería', 'Doctora', '2022-04-15', '2022-04-19');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V047', 'Miguel Serrano', 'Carrera 3 #78-90, Neiva', 'Periodista', '2022-04-16', '2022-04-20');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V048', 'Carolina Morales', 'Avenida 4 #89-01, Sincelejo', 'Psicóloga', '2022-04-17', '2022-04-21');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V049', 'Jorge Vargas', 'Calle 7 #90-12, Medellín', 'Empresario', '2022-04-18', '2022-04-22');
INSERT INTO Visitante (cedula, nombre, direccion, profesion, fecha_entrada, fecha_salida) VALUES ('V050', 'Daniela López', 'Carrera 5 #01-23, Bogotá', 'Ingeniera', '2022-04-19', '2022-04-23');

-- 10. Alojamiento (50 filas)
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (3, 30, 'Hotel', '2023-05-01', '2023-05-07');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (7, 20, 'Hostal', '2023-05-02', '2023-05-08');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (12, 25, 'Cabaña', '2023-05-03', '2023-05-09');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (5, 40, 'Camping', '2023-05-04', '2023-05-10');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (10, 35, 'Hotel', '2023-05-05', '2023-05-11');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (2, 50, 'Resort', '2023-05-06', '2023-05-12');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (15, 45, 'Hostal', '2023-05-07', '2023-05-13');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (20, 30, 'Cabaña', '2023-05-08', '2023-05-14');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (25, 60, 'Camping', '2023-05-09', '2023-05-15');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (30, 55, 'Resort', '2023-05-10', '2023-05-16');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (35, 40, 'Hotel', '2023-05-11', '2023-05-17');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (40, 25, 'Hostal', '2023-05-12', '2023-05-18');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (45, 35, 'Cabaña', '2023-05-13', '2023-05-19');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (50, 45, 'Camping', '2023-05-14', '2023-05-20');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (1, 50, 'Resort', '2023-05-15', '2023-05-21');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (4, 30, 'Hotel', '2023-05-16', '2023-05-22');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (6, 20, 'Hostal', '2023-05-17', '2023-05-23');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (8, 25, 'Cabaña', '2023-05-18', '2023-05-24');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (9, 40, 'Camping', '2023-05-19', '2023-05-25');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (11, 35, 'Resort', '2023-05-20', '2023-05-26');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (13, 45, 'Hotel', '2023-05-21', '2023-05-27');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (14, 50, 'Hostal', '2023-05-22', '2023-05-28');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (16, 30, 'Cabaña', '2023-05-23', '2023-05-29');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (17, 25, 'Camping', '2023-05-24', '2023-05-30');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (18, 40, 'Resort', '2023-05-25', '2023-05-31');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (19, 35, 'Hotel', '2023-05-26', '2023-06-01');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (21, 45, 'Hostal', '2023-05-27', '2023-06-02');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (22, 50, 'Cabaña', '2023-05-28', '2023-06-03');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (23, 30, 'Camping', '2023-05-29', '2023-06-04');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (24, 25, 'Resort', '2023-05-30', '2023-06-05');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (26, 40, 'Hotel', '2023-05-31', '2023-06-06');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (27, 35, 'Hostal', '2023-06-01', '2023-06-07');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (28, 45, 'Cabaña', '2023-06-02', '2023-06-08');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (29, 50, 'Camping', '2023-06-03', '2023-06-09');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (31, 30, 'Resort', '2023-06-04', '2023-06-10');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (32, 25, 'Hotel', '2023-06-05', '2023-06-11');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (33, 40, 'Hostal', '2023-06-06', '2023-06-12');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (34, 35, 'Cabaña', '2023-06-07', '2023-06-13');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (36, 45, 'Camping', '2023-06-08', '2023-06-14');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (37, 50, 'Resort', '2023-06-09', '2023-06-15');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (38, 30, 'Hotel', '2023-06-10', '2023-06-16');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (39, 25, 'Hostal', '2023-06-11', '2023-06-17');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (41, 40, 'Cabaña', '2023-06-12', '2023-06-18');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (42, 35, 'Camping', '2023-06-13', '2023-06-19');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (43, 45, 'Resort', '2023-06-14', '2023-06-20');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (44, 50, 'Hotel', '2023-06-15', '2023-06-21');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (46, 30, 'Hostal', '2023-06-16', '2023-06-22');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (47, 25, 'Cabaña', '2023-06-17', '2023-06-23');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (48, 40, 'Camping', '2023-06-18', '2023-06-24');
INSERT INTO Alojamiento (id_parque, capacidad, categoria, fecha_ingreso, fecha_salida) VALUES (49, 35, 'Resort', '2023-06-19', '2023-06-25');

-- 11. Departamento_Parque (50 filas)
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (1, 3);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (2, 7);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (3, 15);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (4, 22);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (5, 10);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (6, 28);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (7, 35);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (8, 42);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (9, 50);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (10, 6);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (11, 12);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (12, 18);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (13, 24);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (14, 30);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (15, 36);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (16, 44);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (17, 2);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (18, 8);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (19, 14);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (20, 20);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (21, 26);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (22, 32);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (23, 38);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (24, 45);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (25, 5);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (26, 11);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (27, 17);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (28, 23);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (29, 29);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (30, 35);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (31, 41);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (32, 47);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (33, 3);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (34, 9);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (35, 16);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (36, 21);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (37, 27);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (38, 33);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (39, 39);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (40, 45);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (41, 49);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (42, 6);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (43, 13);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (44, 19);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (45, 25);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (46, 31);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (47, 37);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (48, 43);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (49, 50);
INSERT INTO Departamento_Parque (id_departamento, id_parque) VALUES (50, 1);

-- 12. Departamento_Entidad (50 filas)
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (1, 2);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (2, 4);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (3, 6);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (4, 8);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (5, 10);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (6, 12);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (7, 14);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (8, 16);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (9, 18);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (10, 20);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (11, 22);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (12, 24);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (13, 26);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (14, 28);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (15, 30);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (16, 32);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (17, 34);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (18, 36);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (19, 38);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (20, 40);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (21, 42);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (22, 44);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (23, 46);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (24, 48);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (25, 50);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (26, 1);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (27, 3);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (28, 5);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (29, 7);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (30, 9);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (31, 11);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (32, 13);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (33, 15);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (34, 17);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (35, 19);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (36, 21);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (37, 23);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (38, 25);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (39, 27);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (40, 29);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (41, 31);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (42, 33);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (43, 35);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (44, 37);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (45, 39);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (46, 41);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (47, 43);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (48, 45);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (49, 47);
INSERT INTO Departamento_Entidad (id_departamento, id_entidad) VALUES (50, 49);

-- 13. Area_Especie (50 filas)
-- Fórmula: id_especie = ((id_area * 2) mod 50) + 1, cantidad_inventario = (id_area * 3 + 5)
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (1, 3, 8);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (2, 5, 11);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (3, 7, 14);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (4, 9, 17);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (5, 11, 20);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (6, 13, 23);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (7, 15, 26);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (8, 17, 29);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (9, 19, 32);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (10, 21, 35);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (11, 23, 38);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (12, 25, 41);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (13, 27, 44);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (14, 29, 47);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (15, 31, 50);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (16, 33, 53);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (17, 35, 56);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (18, 37, 59);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (19, 39, 62);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (20, 41, 65);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (21, 43, 68);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (22, 45, 71);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (23, 47, 74);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (24, 49, 77);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (25, 1, 80);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (26, 3, 83);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (27, 5, 86);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (28, 7, 89);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (29, 9, 92);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (30, 11, 95);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (31, 13, 98);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (32, 15, 101);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (33, 17, 104);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (34, 19, 107);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (35, 21, 110);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (36, 23, 113);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (37, 25, 116);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (38, 27, 119);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (39, 29, 122);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (40, 31, 125);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (41, 33, 128);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (42, 35, 131);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (43, 37, 134);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (44, 39, 137);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (45, 41, 140);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (46, 43, 143);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (47, 45, 146);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (48, 47, 149);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (49, 49, 152);
INSERT INTO Area_Especie (id_area, id_especie, cantidad_inventario) VALUES (50, 1, 155);

-- 14. Proyecto_Investigador (50 filas)
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (1, 10);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (2, 20);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (3, 30);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (4, 40);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (5, 50);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (6, 1);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (7, 2);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (8, 3);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (9, 4);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (10, 5);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (11, 6);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (12, 7);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (13, 8);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (14, 9);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (15, 10);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (16, 11);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (17, 12);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (18, 13);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (19, 14);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (20, 15);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (21, 16);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (22, 17);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (23, 18);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (24, 19);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (25, 20);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (26, 21);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (27, 22);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (28, 23);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (29, 24);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (30, 25);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (31, 26);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (32, 27);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (33, 28);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (34, 29);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (35, 30);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (36, 31);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (37, 32);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (38, 33);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (39, 34);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (40, 35);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (41, 36);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (42, 37);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (43, 38);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (44, 39);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (45, 40);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (46, 41);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (47, 42);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (48, 43);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (49, 44);
INSERT INTO Proyecto_Investigador (id_proyecto, id_personal) VALUES (50, 45);

-- 15. Proyecto_Especie (50 filas)
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (1, 5);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (2, 10);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (3, 15);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (4, 20);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (5, 25);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (6, 30);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (7, 35);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (8, 40);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (9, 45);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (10, 50);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (11, 4);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (12, 9);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (13, 14);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (14, 19);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (15, 24);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (16, 29);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (17, 34);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (18, 39);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (19, 44);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (20, 49);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (21, 3);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (22, 8);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (23, 13);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (24, 18);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (25, 23);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (26, 28);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (27, 33);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (28, 38);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (29, 43);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (30, 48);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (31, 2);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (32, 7);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (33, 12);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (34, 17);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (35, 22);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (36, 27);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (37, 32);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (38, 37);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (39, 42);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (40, 47);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (41, 1);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (42, 6);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (43, 11);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (44, 16);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (45, 21);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (46, 26);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (47, 31);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (48, 36);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (49, 41);
INSERT INTO Proyecto_Especie (id_proyecto, id_especie) VALUES (50, 46);

-- 16. Visitante_Alojamiento (50 filas)
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (1, 3);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (2, 6);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (3, 9);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (4, 12);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (5, 15);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (6, 18);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (7, 21);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (8, 24);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (9, 27);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (10, 30);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (11, 33);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (12, 36);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (13, 39);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (14, 42);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (15, 45);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (16, 48);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (17, 1);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (18, 4);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (19, 7);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (20, 10);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (21, 13);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (22, 16);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (23, 19);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (24, 22);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (25, 25);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (26, 28);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (27, 31);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (28, 34);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (29, 37);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (30, 40);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (31, 43);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (32, 46);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (33, 49);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (34, 2);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (35, 5);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (36, 8);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (37, 11);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (38, 14);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (39, 17);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (40, 20);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (41, 23);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (42, 26);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (43, 29);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (44, 32);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (45, 35);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (46, 38);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (47, 41);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (48, 44);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (49, 47);
INSERT INTO Visitante_Alojamiento (id_visitante, id_alojamiento) VALUES (50, 50);
